---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1wyaa3trkjmdnq9a6wf2twkmwhqtx2j8s9f4zdlqamxlhy5fkxd6q4u00fw"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1wyaa3trkjmdnq9a6wf2twkmwhqtx2j8s9f4zdlqamxlhy5fkxd6q4u00fw"
