---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kubernetes/apps/podinfo/app
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  timeout: 3m0s
  wait: true
